version: '3'
services:
  web:
    build: .
    command: ./bin/rails server
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      PORT: "3000"
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - dev-volume:/app/db

volumes:
  dev-volume:
