version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      PORT: "3000"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/app/db
